const supa = require('./lib/supabase')
const eleven = require('./lib/elevenlabs')
function getAdminSecret(){ const prod = (process.env.ADMIN_SECRET || '').trim(); const dev = (process.env.ADMIN_SECRET_DEV || '').trim(); const env = (process.env.NODE_ENV || '').trim().toLowerCase(); return env==='development' ? (dev || prod) : prod }
function isAdmin(req){ const s = getAdminSecret(); const h = (req.headers['x-admin-secret'] || '').trim(); return s && h && s===h }
async function setPlan(req,res){ try{ if(!isAdmin(req)) return res.status(401).json({ error:'unauthorized' }); const userId = req.body.user_id || ''; const plan = (req.body.plan || '').toLowerCase(); if(!userId || !plan) return res.status(400).json({ error:'missing_params' }); if(!['free','basic','standard','pro','team','executive_pro_annual','premium'].includes(plan)) return res.status(400).json({ error:'invalid_plan' }); await supa.setUserPlan(userId, plan); try{ await supa.client.from('users').update({ plan }).eq('google_id', userId) }catch(_){} res.json({ ok:true }) }catch(e){ res.status(500).json({ error:'server_error' }) } }
async function removeVoice(req,res){ try{ if(!isAdmin(req)) return res.status(401).json({ error:'unauthorized' }); const userId = req.body.user_id || ''; const deviceId = req.body.device_id || ''; if(!userId || !deviceId) return res.status(400).json({ error:'missing_params' }); const voiceId = await supa.getDeviceVoice(userId, deviceId); if(voiceId){ try{ await eleven.deleteVoice(voiceId) }catch(e){} } await supa.clearDeviceVoice(userId, deviceId); res.json({ ok:true }) }catch(e){ res.status(500).json({ error:'server_error' }) } }
async function setDeviceVoiceManual(req,res){ try{ if(!isAdmin(req)) return res.status(401).json({ error:'unauthorized' }); const userId = req.body.user_id || ''; const deviceId = req.body.device_id || ''; const voiceId = req.body.voice_id || ''; if(!userId || !deviceId || !voiceId) return res.status(400).json({ error:'missing_params' }); await supa.setDeviceVoice(userId, deviceId, voiceId); res.json({ ok:true }) }catch(e){ res.status(500).json({ error:'server_error' }) } }
async function setVoiceChangeStatus(req,res){ try{ if(!isAdmin(req)) return res.status(401).json({ error:'unauthorized' }); const orderId = req.body.order_id || ''; const status = (req.body.status || '').toLowerCase(); if(!orderId || !status) return res.status(400).json({ error:'missing_params' }); await supa.client.from('voice_changes').update({ status }).eq('order_id', orderId); res.json({ ok:true }) }catch(e){ res.status(500).json({ error:'server_error' }) } }
module.exports = { setPlan, removeVoice, setDeviceVoiceManual, setVoiceChangeStatus }
